# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [6]:
print(np.__version__)
np.show_config

1.23.4


<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [7]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [19]:
L=[1,4,2,7,3,9]
a=np.array(L)
print('size : ',a.size)
print('itemsize:',a.itemsize)
print('the memory size of array:',a.size*a.itemsize)

size :  6
itemsize: 4
the memory size of array: 24


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [28]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [54]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [31]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [35]:
a=np.arange(10,50)
a=a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [56]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [57]:
a=np.nonzero( [1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [60]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [65]:
a = np.random.random((3,3,3))
print(a)

[[[0.84633623 0.55687644 0.98733746]
  [0.28030405 0.52379358 0.92729023]
  [0.98237156 0.08396885 0.0996901 ]]

 [[0.13268945 0.60179553 0.13151752]
  [0.72414397 0.3039885  0.88038003]
  [0.89096786 0.17390422 0.84813189]]

 [[0.30555438 0.56017378 0.50207397]
  [0.32817507 0.3128905  0.41222281]
  [0.0100322  0.8124241  0.17564868]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [75]:
a = np.random.random((10,10))
print(a)
print('minimum values:',a.min())
print(' maximum values :',a.max())

[[0.3554172  0.47464895 0.60690912 0.5743918  0.10714227 0.54576443
  0.37626474 0.0582036  0.26376667 0.7751439 ]
 [0.17204572 0.66195974 0.31425116 0.3979694  0.24186019 0.04809383
  0.37512597 0.48359944 0.3015829  0.32616836]
 [0.10874527 0.51571768 0.05510571 0.57848886 0.41455112 0.51641278
  0.00368832 0.33503223 0.83722424 0.37156644]
 [0.16613444 0.57019066 0.11551921 0.27556061 0.92481698 0.54302698
  0.9927853  0.56310167 0.2033852  0.21756279]
 [0.03117699 0.78546081 0.86290577 0.73090831 0.56993622 0.29099673
  0.78499755 0.67668673 0.84520838 0.28777201]
 [0.70052454 0.45014112 0.66512426 0.67683486 0.74180633 0.79796723
  0.18073782 0.4949755  0.613342   0.27043021]
 [0.96022411 0.46551488 0.1199732  0.45257743 0.1845192  0.68741558
  0.70625511 0.12152524 0.42179173 0.69309371]
 [0.66745662 0.27760579 0.84943603 0.87388628 0.82861218 0.14628209
  0.20928932 0.37548157 0.75219585 0.55609859]
 [0.50507271 0.85430133 0.22048827 0.89165681 0.11847921 0.68529728
  0.84664686

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [80]:
a=np.random.random(30)
print(a.mean())

0.555645702907397


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [84]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [93]:
a = np.ones((3,3))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [96]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [97]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [98]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [99]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [100]:
a = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [101]:
a = np.random.random((5,5))
a = (a - np.mean (a)) / (np.std (a))
print(a)

[[ 0.54763045 -1.38339213 -1.35321566  0.12628964 -1.17826487]
 [-0.84945147  1.62753049  0.43488921 -0.92499641  0.11929358]
 [-1.40105037 -0.38779486 -0.31096946  1.11772631 -0.14819685]
 [ 0.55373195  1.58858599 -1.32057049  0.01710423  1.53000836]
 [ 0.65382893  1.32626653  0.58125077  0.44792872 -1.41416258]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [94]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\SJL\AppData\Local\Temp\ipykernel_8208\2911720781.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [102]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)
a = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [103]:
a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [105]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [3]:
#Z<Z>Z not legal


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [3]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\SJL\AppData\Local\Temp\ipykernel_7468\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\SJL\AppData\Local\Temp\ipykernel_7468\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [6]:
a = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(a)), a))

[-10.  -4.   9. -10.   2.   8.  -3.   6.  -3.  -3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [10]:
a = np.random.randint(0,10,10)
A = np.random.randint(0,10,10)
print(np.intersect1d(a,A))

[0 1 3 4 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [14]:
defaults = np.seterr(all="ignore")
a = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
  a =  np.ones(1) / 0
print(a)

[inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [15]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\SJL\AppData\Local\Temp\ipykernel_9308\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [17]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-11-11
2022-11-12
2022-11-13


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [21]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [27]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [28]:
a = np.random.uniform(0,10,10)

print (a - a%1)
print (np.floor(a))
print (np.ceil(a)-1)
print (a.astype(int))
print (np.trunc(a))

[2. 5. 9. 9. 0. 5. 7. 2. 1. 4.]
[2. 5. 9. 9. 0. 5. 7. 2. 1. 4.]
[2. 5. 9. 9. 0. 5. 7. 2. 1. 4.]
[2 5 9 9 0 5 7 2 1 4]
[2. 5. 9. 9. 0. 5. 7. 2. 1. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [31]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [32]:
def generate():
    for i in range(10):
        yield i
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [33]:
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [38]:
a = np.random.random(10)
a.sort()
print(a)

[0.09593239 0.2847476  0.48272985 0.49806802 0.58026893 0.5945334
 0.75641066 0.77873201 0.83898928 0.87335653]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [41]:
a=np.arange(5)
print(a)
print(np.add.reduce(a))

[0 1 2 3 4]
10


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [42]:
a = np.random.randint(0,2,10)
b = np.random.randint(0,2,10)
equal = np.allclose(a,b)
print(equal)
equal = np.array_equal(a,b)
print(equal)



False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [47]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [48]:
a = np.random.random((10,2))
X,Y = a[:,0], a[:,1]
b = np.sqrt(X**2+Y**2)
c = np.arctan2(Y,X)
print(b)
print(c)

[0.41170156 0.9790402  0.8885276  1.14784349 0.18303192 0.7805136
 0.86427398 1.33150248 0.82319662 0.7572009 ]
[1.06118291 0.01718182 0.2284884  0.99388835 1.30896012 0.8087788
 0.14679752 0.76069659 1.51245018 0.19114597]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [49]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)


[0.9360648  0.         0.59759519 0.9289983  0.88721553 0.17371982
 0.91298503 0.79076124 0.2257151  0.01333904]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [52]:
a = np.zeros((4,4), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,4),
                             np.linspace(0,1,4))
print(a)

[[(0.        , 0.        ) (0.33333333, 0.        )
  (0.66666667, 0.        ) (1.        , 0.        )]
 [(0.        , 0.33333333) (0.33333333, 0.33333333)
  (0.66666667, 0.33333333) (1.        , 0.33333333)]
 [(0.        , 0.66666667) (0.33333333, 0.66666667)
  (0.66666667, 0.66666667) (1.        , 0.66666667)]
 [(0.        , 1.        ) (0.33333333, 1.        )
  (0.66666667, 1.        ) (1.        , 1.        )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [53]:
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

33961.93294480225


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [54]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [63]:
np.set_printoptions()
a=np.ones((10,10))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [110]:
a = np.arange(100)
b = np.random.uniform(0,100)
index = (np.abs(a-b)).argmin()
print(a[index])

7


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [112]:
a = np.ones(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


D:\anaconda\miniconda3\lib\site-packages\numpy\core\numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [119]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.34117968 0.25485065 0.66696858 0.9113939  0.93893245
  0.07238827 1.03865894 0.51374955 0.30608705]
 [0.34117968 0.         0.29676569 0.40506858 0.61295057 0.59846664
  0.33154188 0.70817945 0.21125214 0.132702  ]
 [0.25485065 0.29676569 0.         0.700533   0.71541201 0.84321786
  0.30941962 0.87991349 0.3615756  0.36417568]
 [0.66696858 0.40506858 0.700533   0.         0.73160891 0.45090376
  0.619907   0.69198398 0.48208644 0.36437503]
 [0.9113939  0.61295057 0.71541201 0.73160891 0.         0.42059151
  0.92613952 0.23195693 0.40520988 0.7331413 ]
 [0.93893245 0.59846664 0.84321786 0.45090376 0.42059151 0.
  0.92075947 0.27296912 0.48704134 0.65936078]
 [0.07238827 0.33154188 0.30941962 0.619907   0.92613952 0.92075947
  0.         1.03877522 0.5225684  0.26930635]
 [1.03865894 0.70817945 0.87991349 0.69198398 0.23195693 0.27296912
  1.03877522 0.         0.52862639 0.80593891]
 [0.51374955 0.21125214 0.3615756  0.48208644 0.40520988 0.48704134
  0.5225684  0.52862

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
a = np.arange(10,dtype=np.float32)
a=a.astype(copy=False)
print(a)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [121]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
a = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\SJL\AppData\Local\Temp\ipykernel_9308\530937926.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [122]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) -1
(1, 2) -1
(1, 3) 7
(1, 4) 8
(2, 0) -1
(2, 1) -1
(2, 2) 9
(2, 3) 10
(2, 4) 11
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [123]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [125]:
n = 10
p = 3
a= np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [126]:
a = np.random.rand(5, 10)

# Recent versions of numpy
b = a - a.mean(axis=1, keepdims=True)

# Older versions of numpy
b = a - a.mean(axis=1).reshape(-1, 1)

print(b)

[[ 0.00576613 -0.38701687  0.48859988 -0.18512569  0.09958367 -0.18065374
  -0.3183559   0.30543023  0.29450958 -0.12273728]
 [ 0.49923373  0.00974083 -0.33909445 -0.38042164 -0.01424168  0.34420273
   0.14418404 -0.28985453 -0.42944124  0.4556922 ]
 [-0.07652293  0.04796182  0.23909354  0.42024319  0.22243616 -0.10458544
  -0.48543338  0.03267108 -0.21865031 -0.07721373]
 [ 0.21701698  0.00099794 -0.3304838  -0.00817738 -0.0886419  -0.13554617
  -0.26615352  0.32781901  0.1722002   0.11096864]
 [ 0.45847308 -0.26921163  0.10994504 -0.40036119 -0.41566202 -0.31772436
   0.46419926  0.11726541  0.45548602 -0.20240963]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [128]:
a=np.random.randint(0,10,(2,2))
print(a)
print(a[a[:,1].argsort()])

[[7 6]
 [2 0]]
[[2 0]
 [7 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [141]:
a=np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [143]:
a = np.random.uniform(0,1,10)
b = 0.5
c = a.flat[np.abs(a - b).argmin()]
print(c)

0.4885030082984676


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [145]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [146]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

a = NamedArray(np.arange(10), "range_10")
print (a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [148]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

np.add.at(a, b, 1)
print(a)

[2. 2. 3. 4. 3. 4. 2. 6. 1. 3.]
[ 3.  3.  5.  7.  5.  7.  3. 11.  1.  5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [150]:
X = [1,2,3,4,5,6]
I = [1,2,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 2. 4. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [153]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
n = len(np.unique(I))
print(n)

2


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [154]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[32 65 51 56]
 [78 40 55 56]
 [68 46 53 56]]
[[32 65 51 56]
 [78 40 55 56]
 [68 46 53 56]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [155]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.60225662 0.5488413  0.59446832 0.61913551 0.49145947 0.35170493
 0.54901463 0.48561128 0.6705278  0.52025451]
0    0.602257
1    0.548841
2    0.594468
3    0.619136
4    0.491459
5    0.351705
6    0.549015
7    0.485611
8    0.670528
9    0.520255
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [156]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.45662589 0.50403068 0.47593328 0.57527961 0.44591594 0.57500051
 0.57972696 0.53179576 0.33882466 0.4994726 ]
0    0.456626
1    0.504031
2    0.475933
3    0.575280
4    0.445916
5    0.575001
6    0.579727
7    0.531796
8    0.338825
9    0.499473
dtype: float64


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [157]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [158]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [159]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [160]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 52) ( 0, 66) ( 2, 30) ( 2, 73) ( 3,  4) ( 3, 77) ( 4, 77) (10, 17)
 (10, 29) (10, 90) (10, 99) (12, 19) (12, 80) (13, 49) (13, 67) (17, 90)
 (19, 80) (25, 35) (25, 85) (29, 99) (30, 73) (35, 85) (38, 53) (38, 81)
 (49, 67) (52, 66) (53, 81) (69, 72) (69, 99) (72, 99)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [161]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [162]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [3]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [163]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.52253252,  0.35168303,  0.09324569, -0.17577972, -0.04075402,
        0.29014791, -0.80890269,  0.10074115,  0.69934476, -0.83304109,
        0.96802344, -0.06310519,  0.88678407,  0.97529255,  0.97315796,
        0.37845918,  0.90088592,  0.88959485, -0.50063347, -0.83428513,
       -0.50282457,  0.78857882,  0.8774056 ,  0.43236197, -0.59525166,
        0.94483907, -0.16324195,  0.2076523 ,  0.90516671, -0.46314621,
       -0.09643762, -0.99341313,  0.00823576,  0.41931527,  0.39931111,
       -0.53273518, -0.85583767, -0.26156362, -0.29277749,  0.6912035 ,
       -0.75808248,  0.66757582,  0.8222521 ,  0.41842212,  0.75489852,
        0.75556343,  0.49909123, -0.46439935,  0.22031306, -0.42139102,
        0.65332982,  0.22416983,  0.69103216, -0.91017945, -0.58039526,
        0.59681422,  0.53716284,  0.76727157,  0.42437471, -0.63910999,
       -0.24471334,  0.64363643,  0.84743769, -0.78501998, -0.87809777,
        0.84612153,  0.83537414,  0.37032405, -0.34951832,  0.18

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [164]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[12.58301636  4.83395104  9.82145553  4.45746683  7.79166386  9.86922083
  8.95790624  1.30772649  1.16264413  3.77854223]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [165]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.1361419  13.34680808  7.12906052  3.55060523 15.39209713  1.72140387
  10.34450829  4.33158845  4.31507363  7.15299744]
 [ 3.24483205 10.4050133   1.76717857  1.66751488  6.00315288  4.65819687
   2.70715899  2.79697769  4.54894445  2.30362519]
 [ 1.22628898  2.67289043 14.36172512  6.48923614 11.73769017  7.45406544
   2.23673225  4.34952381  5.69439744  4.56963371]
 [ 4.37225294  4.20151611  1.92662619  8.8501478   0.72917855  2.33066489
   4.97550054 10.44623232  8.82992177  8.61299428]
 [ 0.93261037  0.83158764 17.67104956  7.53412688 13.45667262 10.56887237
   2.35249019  4.51957072  8.52345115  6.57508613]
 [ 1.47280274  5.83348285  3.36977041  6.46570264  2.73426395  1.83941845
   1.86353402  7.47768621  5.83723576  5.18755581]
 [ 4.9907587   0.76087825 11.13222519 11.57059509  4.23040627  6.27701358
   4.45284407 10.71983483  0.84501516  2.86720993]
 [ 8.87629796 10.66860381 10.56177584  1.57067054 16.31893295  1.78311182
   9.49864997  3.19519581  6.69463342  8.4283904 ]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [167]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [168]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

NameError: name 'stride_tricks' is not defined

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [169]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [4]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 4 1]
   [2 1 2]
   [2 3 0]]

  [[4 1 1]
   [1 2 0]
   [3 0 1]]

  [[1 1 1]
   [2 0 1]
   [0 1 0]]

  [[1 1 3]
   [0 1 1]
   [1 0 0]]

  [[1 3 1]
   [1 1 1]
   [0 0 3]]

  [[3 1 0]
   [1 1 4]
   [0 3 2]]

  [[1 0 4]
   [1 4 0]
   [3 2 4]]

  [[0 4 4]
   [4 0 3]
   [2 4 4]]]


 [[[2 1 2]
   [2 3 0]
   [4 3 0]]

  [[1 2 0]
   [3 0 1]
   [3 0 4]]

  [[2 0 1]
   [0 1 0]
   [0 4 2]]

  [[0 1 1]
   [1 0 0]
   [4 2 4]]

  [[1 1 1]
   [0 0 3]
   [2 4 1]]

  [[1 1 4]
   [0 3 2]
   [4 1 2]]

  [[1 4 0]
   [3 2 4]
   [1 2 4]]

  [[4 0 3]
   [2 4 4]
   [2 4 1]]]


 [[[2 3 0]
   [4 3 0]
   [4 0 2]]

  [[3 0 1]
   [3 0 4]
   [0 2 1]]

  [[0 1 0]
   [0 4 2]
   [2 1 1]]

  [[1 0 0]
   [4 2 4]
   [1 1 3]]

  [[0 0 3]
   [2 4 1]
   [1 3 1]]

  [[0 3 2]
   [4 1 2]
   [3 1 4]]

  [[3 2 4]
   [1 2 4]
   [1 4 4]]

  [[2 4 4]
   [2 4 1]
   [4 4 2]]]


 [[[4 3 0]
   [4 0 2]
   [4 2 0]]

  [[3 0 4]
   [0 2 1]
   [2 0 3]]

  [[0 4 2]
   [2 1 1]
   [0 3 2]]

  [[4 2 4]
   [1 1 3]
   [3 2 1]]

  [[2 4 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [170]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1  6  7  4  2]
 [ 6  0 11  9  2]
 [ 7 11  0 42  4]
 [ 4  9 42  4 11]
 [ 2  2  4 11  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [171]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [172]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [173]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [174]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [175]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [176]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [177]:

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.75 µs ± 156 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.87 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


ValueError: einstein sum subscripts string contains too many subscripts for operand 0

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [178]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [179]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 3 2]
 [1 4 4]
 [0 1 0]
 [2 4 0]
 [1 3 0]
 [0 3 2]
 [0 1 4]
 [2 1 2]
 [4 0 4]
 [3 1 2]]
[[0 3 2]
 [1 4 4]
 [0 1 0]
 [2 4 0]
 [1 3 0]
 [0 3 2]
 [0 1 4]
 [2 1 2]
 [4 0 4]
 [3 1 2]]
[[0 3 2]
 [1 4 4]
 [0 1 0]
 [2 4 0]
 [1 3 0]
 [0 3 2]
 [0 1 4]
 [2 1 2]
 [4 0 4]
 [3 1 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [128]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [127]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]
[[0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [126]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[1.80132770e-01, 4.69044882e-01, 1.13083040e-01, 5.56359460e-02,
        1.20736423e-01, 3.00471730e-02, 4.28458020e-01, 2.30993845e-01,
        2.53278469e-01, 1.33125421e-01],
       [6.09995251e-02, 1.58835703e-01, 3.82940415e-02, 1.88403603e-02,
        4.08857559e-02, 1.01750686e-02, 1.45091511e-01, 7.82229402e-02,
        8.57693265e-02, 4.50811224e-02],
       [2.71434773e-02, 7.06784730e-02, 1.70400252e-02, 8.38355530e-03,
        1.81932824e-02, 4.52768677e-03, 6.45626032e-02, 3.48075267e-02,
        3.81655064e-02, 2.00601303e-02],
       [2.23452133e-01, 5.81843489e-01, 1.40277899e-01, 6.90155978e-02,
        1.49771811e-01, 3.72730897e-02, 5.31496065e-01, 2.86544572e-01,
        3.14188330e-01, 1.65140186e-01],
       [2.66275934e-02, 6.93351710e-02, 1.67161657e-02, 8.22421900e-03,
        1.78475042e-02, 4.44163439e-03, 6.33355383e-02, 3.41459813e-02,
        3.74401399e-02, 1.96788712e-02],
       [1.51778022e-04, 3.95212400e-04, 9.52826083e-05, 4.68782766e-05,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [125]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)
print(x_int)
print('<<< ' , y_int)

[ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  5.28038

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [115]:
X = np.asarray([[1.0, 1.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [117]:
X = np.random.randn(100) 
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.10412708  0.31151094]
